name: CI

on:
  push:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Hotels
        id: docker_build_hotels
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: tpiechocki/rsww_175641_hotel:latest
          file: ./TripBooker.HotelService/Dockerfile
      -
        name: Build and push Payment
        id: docker_build_payment
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: tpiechocki/rsww_175641_payment:latest
          file: ./TripBooker.PaymentService/Dockerfile
      -
        name: Build and push Tour Operator
        id: docker_build_tour_operator
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: tpiechocki/rsww_175641_tour_operator:latest
          file: ./TripBooker.TourOperator/Dockerfile
      -
        name: Build and push Transport
        id: docker_build_transport
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: tpiechocki/rsww_175641_transport:latest
          file: ./TripBooker.TransportService/Dockerfile
      -
        name: Build and push Travel Agency
        id: docker_build_travel_agency
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: tpiechocki/rsww_175641_travel_agency:latest
          file: ./TripBooker.TravelAgencyService/Dockerfile
      -
        name: Build and push WebApi
        id: docker_build_webapi
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:backend"
          push: true
          tags: tpiechocki/rsww_175641_webapi:latest
          file: ./TripBooker.WebApi/Dockerfile
      -
        name: Build and push Frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with: 
          context: "{{defaultContext}}:frontend"
          push: true
          tags: tpiechocki/rsww_175641_frontend:latest
          build-args:
            WEB_API_URL=http://localhost:17565/
